"""Tier-1 tests against fixtures produced by the *actual Isca Fortran*.

Fixtures are generated by ``fortran_instrumentation/dump_grid_reference.F90``
(compiled against the real ``gauss_and_legendre.F90``) and stored as
``tests/fixtures/grid_reference_t42.npz``. If the file is absent, these tests
skip — regenerate with the recipe in ``fortran_instrumentation/README.md``.

Tolerances: same algorithm, same IEEE float64 — differences are compiler
instruction-selection only, so demand near-ulp agreement.
"""

from pathlib import Path

import numpy as np
import pytest

from jsca.grid import Truncation, compute_legendre, gaussian_grid, gaussian_hemisphere

FIXTURE = Path(__file__).parent / "fixtures" / "grid_reference_t42.npz"

pytestmark = pytest.mark.skipif(not FIXTURE.exists(), reason="Fortran fixtures not generated")


@pytest.fixture(scope="module")
def fx():
    return np.load(FIXTURE)


def test_gaussian_nodes_match_fortran(fx):
    sin_hem, wts_hem = gaussian_hemisphere(32)
    np.testing.assert_allclose(sin_hem, fx["sin_hem"], rtol=0, atol=5e-16)
    np.testing.assert_allclose(wts_hem, fx["wts_hem"], rtol=1e-14)


def test_global_assembly_matches_fortran(fx):
    gg = gaussian_grid(64)
    np.testing.assert_allclose(gg.sin_lat, fx["sin_lat_global"], rtol=0, atol=5e-16)


def test_legendre_match_fortran(fx):
    gg = gaussian_grid(64)
    mine = compute_legendre(Truncation(42), gg.sin_lat)  # (nlat, m, n)
    theirs = fx["legendre_t42"].transpose(2, 0, 1)  # Fortran (m, n, nlat) -> (nlat, m, n)
    np.testing.assert_allclose(mine, theirs, rtol=1e-13, atol=1e-14)
