"""Frierson moist-aquaplanet climatology: jsca vs the real Isca run (T42).

Loads the committed zonal-mean references in ``baseline/reference/`` — one from a
real pinned-Isca ``frierson_test_case`` run, one from a matching jsca
``FriersonModel`` run (both T42, 60 days, days 30-end time-mean) — reports the
skill statistics, and writes the comparison figure.

Both runs and the references are regenerated by:
  * Isca — ``fortran_instrumentation/frierson_step_recipe.md`` (build + run at T42);
  * jsca — ``jsca.model.frierson.integrate_climatology``.

This is a **first benchmark**, not the statistical-parity finish line: 60 days from
an isothermal rest state is too short for the eddy-driven jet to equilibrate (see
``docs/frierson_climatology.md``). Run: ``python scripts/compare_frierson_climatology.py``
"""
from pathlib import Path

import matplotlib
import numpy as np

matplotlib.use("Agg")
import matplotlib.pyplot as plt  # noqa: E402

ROOT = Path(__file__).resolve().parent.parent
I = np.load(ROOT / "baseline" / "reference" / "frierson_isca_zonalmean_t42_60day.npz")
J = np.load(ROOT / "baseline" / "reference" / "frierson_jsca_zonalmean_t42_60day.npz")

lat_i, pfull = I["lat"], I["pfull"]
lat_j = J["lat_jsca"]


def to_isca_lat(a):
    """Interpolate a jsca zonal-mean profile (lat_j[, lev]) onto Isca's latitudes."""
    if a.ndim == 1:
        return np.interp(lat_i, lat_j, a)
    return np.stack([np.interp(lat_i, lat_j, a[:, k]) for k in range(a.shape[1])], axis=1)


fields = {  # jsca-key, isca-key, scale, unit
    "u": ("ucomp", "ucomp", 1.0, "m/s"),
    "T": ("temp", "temp", 1.0, "K"),
    "q": ("sphum", "sphum", 1e3, "g/kg"),
    "precip": ("precip", "precip", 86400.0, "mm/day"),
    "t_surf": ("t_surf", "t_surf", 1.0, "K"),
}

print("=== jsca vs Isca Frierson zonal-mean climatology (T42, 60 days, days 30-end) ===")
for name, (jk, ik, sc, unit) in fields.items():
    a = to_isca_lat(J[jk]) * sc
    b = I[ik] * sc
    rmse = np.sqrt(np.nanmean((a - b) ** 2))
    bias = np.nanmean(a - b)
    corr = np.corrcoef(a.ravel(), b.ravel())[0, 1]
    print(f"{name:7s} corr={corr:.4f}  RMSE={rmse:.3g} {unit}  bias={bias:+.3g}  "
          f"(Isca range [{np.nanmin(b):.3g}, {np.nanmax(b):.3g}])")

# --- figure ---
fig, axes = plt.subplots(2, 3, figsize=(16, 9))


def contour(ax, f, title, levels, cmap):
    c = ax.contourf(lat_i, pfull, f.T, levels=levels, cmap=cmap, extend="both")
    ax.invert_yaxis()
    ax.set_title(title)
    ax.set_xlabel("latitude")
    ax.set_ylabel("pressure (hPa)")
    plt.colorbar(c, ax=ax)


u_i, u_j = I["ucomp"], to_isca_lat(J["ucomp"])
t_i, t_j = I["temp"], to_isca_lat(J["temp"])
ulev = np.linspace(-30, 30, 13)
contour(axes[0, 0], u_i, "Isca zonal-mean u (m/s)", ulev, "RdBu_r")
contour(axes[0, 1], u_j, "jsca zonal-mean u (m/s)", ulev, "RdBu_r")
contour(axes[0, 2], u_j - u_i, "u difference (jsca - Isca)", np.linspace(-5, 5, 21), "RdBu_r")
tlev = np.linspace(180, 300, 13)
contour(axes[1, 0], t_i, "Isca zonal-mean T (K)", tlev, "viridis")
contour(axes[1, 1], t_j, "jsca zonal-mean T (K)", tlev, "viridis")

ax = axes[1, 2]
ax.plot(lat_i, I["precip"] * 86400, "k-", label="Isca precip")
ax.plot(lat_i, to_isca_lat(J["precip"]) * 86400, "r--", label="jsca precip")
ax.set_xlabel("latitude")
ax.set_ylabel("precip (mm/day)")
ax.legend(loc="upper left", fontsize=8)
ax.set_title("precipitation & surface temperature")
ax2 = ax.twinx()
ax2.plot(lat_i, I["t_surf"], "b-", alpha=0.5, label="Isca t_surf")
ax2.plot(lat_i, to_isca_lat(J["t_surf"]), "g--", alpha=0.8, label="jsca t_surf")
ax2.set_ylabel("t_surf (K)")
ax2.legend(loc="upper right", fontsize=8)

fig.suptitle("Frierson moist aquaplanet climatology (T42, 60-day, days 30-end mean): jsca vs Isca",
             fontsize=13)
fig.tight_layout(rect=(0, 0, 1, 0.97))
out = ROOT / "docs" / "figures" / "frierson_climatology.png"
fig.savefig(out, dpi=120, bbox_inches="tight")
print("wrote", out)
