"""Frierson moist-aquaplanet climatology: jsca vs the real Isca run (T42).

Loads the committed zonal-mean references in ``baseline/reference/`` — one from a
real pinned-Isca ``frierson_test_case`` run, one from a matching jsca
``FriersonModel`` run — reports the skill statistics, and writes the comparison
figure. Two windows are available:

* ``60day``  — days 30-end of a 60-day run. A **spin-up snapshot**: the mean
  thermal state is established but the eddy-driven jet has only just begun to
  grow (jsca cold-starts isothermal, so it carries no initial baroclinicity).
* ``200day`` — days 100-200 of a 200-day run (the default). Close to
  statistical **equilibrium**: the jet, storm-track precipitation and ITCZ have
  developed, so this is the meaningful jsca-vs-Isca comparison.

Both runs and the references are regenerated by:
  * Isca — ``fortran_instrumentation/frierson_step_recipe.md`` (build + run at T42);
  * jsca — ``jsca.model.frierson.integrate_climatology`` (or the scratch driver).

Run: ``python scripts/compare_frierson_climatology.py [60day|200day]``
See ``docs/frierson_climatology.md`` for the write-up.
"""
import sys
from pathlib import Path

import matplotlib
import numpy as np

matplotlib.use("Agg")
import matplotlib.pyplot as plt  # noqa: E402

ROOT = Path(__file__).resolve().parent.parent

# tag: (description, figure-name, isca-reference, jsca-reference)
WINDOWS = {
    "60day": ("days 30-end of a 60-day run (spin-up snapshot), jsca on an 86x172 grid",
              "frierson_climatology.png",
              "frierson_isca_zonalmean_t42_60day.npz", "frierson_jsca_zonalmean_t42_60day.npz"),
    "200day": ("days 100-200, jsca on an 86x172 grid",
               "frierson_climatology_equilibrium.png",
               "frierson_isca_zonalmean_t42_200day.npz", "frierson_jsca_zonalmean_t42_200day.npz"),
    # like-for-like: jsca on Isca's exact 64x128 grid with Isca's matched initial
    # condition (days 200-300 mean). Reuses the 64-lat Isca 200-day reference.
    "matched": ("jsca on Isca's 64x128 grid + matched IC (days 200-300)",
                "frierson_climatology_matched.png",
                "frierson_isca_zonalmean_t42_200day.npz", "frierson_jsca_zonalmean_t42x64.npz"),
}

fields = {  # name: (npz-key, scale, unit)
    "u": ("ucomp", 1.0, "m/s"),
    "T": ("temp", 1.0, "K"),
    "q": ("sphum", 1e3, "g/kg"),
    "precip": ("precip", 86400.0, "mm/day"),
    "t_surf": ("t_surf", 1.0, "K"),
}


def run(tag):
    desc, figname, isca_ref, jsca_ref = WINDOWS[tag]
    ref = ROOT / "baseline" / "reference"
    I, J = np.load(ref / isca_ref), np.load(ref / jsca_ref)
    lat_i, pfull = I["lat"], I["pfull"]
    lat_j = J["lat_jsca"]

    def to_isca_lat(a):
        """Interpolate a jsca zonal-mean profile (lat_j[, lev]) onto Isca's latitudes."""
        if a.ndim == 1:
            return np.interp(lat_i, lat_j, a)
        return np.stack([np.interp(lat_i, lat_j, a[:, k]) for k in range(a.shape[1])], axis=1)

    print(f"=== jsca vs Isca Frierson zonal-mean climatology (T42, {desc}) ===")
    for name, (k, sc, unit) in fields.items():
        a = to_isca_lat(J[k]) * sc
        b = I[k] * sc
        rmse = np.sqrt(np.nanmean((a - b) ** 2))
        bias = np.nanmean(a - b)
        corr = np.corrcoef(a.ravel(), b.ravel())[0, 1]
        print(f"{name:7s} corr={corr:.4f}  RMSE={rmse:.3g} {unit}  bias={bias:+.3g}  "
              f"(Isca range [{np.nanmin(b):.3g}, {np.nanmax(b):.3g}])")
    if "_perf_ms_per_step" in J:
        perf = float(J["_perf_ms_per_step"])
        print(f"jsca performance: {perf:.1f} ms/step (T42, single-core CPU)")

    # --- figure ---
    fig, axes = plt.subplots(2, 3, figsize=(16, 9))

    def contour(ax, f, title, levels, cmap):
        c = ax.contourf(lat_i, pfull, f.T, levels=levels, cmap=cmap, extend="both")
        ax.invert_yaxis()
        ax.set_title(title)
        ax.set_xlabel("latitude")
        ax.set_ylabel("pressure (hPa)")
        plt.colorbar(c, ax=ax)

    u_i, u_j = I["ucomp"], to_isca_lat(J["ucomp"])
    t_i, t_j = I["temp"], to_isca_lat(J["temp"])
    ulev = np.linspace(-30, 40, 15)
    contour(axes[0, 0], u_i, "Isca zonal-mean u (m/s)", ulev, "RdBu_r")
    contour(axes[0, 1], u_j, "jsca zonal-mean u (m/s)", ulev, "RdBu_r")
    contour(axes[0, 2], u_j - u_i, "u difference (jsca - Isca)", np.linspace(-10, 10, 21), "RdBu_r")
    tlev = np.linspace(180, 300, 13)
    contour(axes[1, 0], t_i, "Isca zonal-mean T (K)", tlev, "viridis")
    contour(axes[1, 1], t_j, "jsca zonal-mean T (K)", tlev, "viridis")

    ax = axes[1, 2]
    ax.plot(lat_i, I["precip"] * 86400, "k-", label="Isca precip")
    ax.plot(lat_i, to_isca_lat(J["precip"]) * 86400, "r--", label="jsca precip")
    ax.set_xlabel("latitude")
    ax.set_ylabel("precip (mm/day)")
    ax.legend(loc="upper left", fontsize=8)
    ax.set_title("precipitation & surface temperature")
    ax2 = ax.twinx()
    ax2.plot(lat_i, I["t_surf"], "b-", alpha=0.5, label="Isca t_surf")
    ax2.plot(lat_i, to_isca_lat(J["t_surf"]), "g--", alpha=0.8, label="jsca t_surf")
    ax2.set_ylabel("t_surf (K)")
    ax2.legend(loc="upper right", fontsize=8)

    fig.suptitle(f"Frierson moist aquaplanet climatology (T42, {desc}): jsca vs Isca", fontsize=13)
    fig.tight_layout(rect=(0, 0, 1, 0.97))
    out = ROOT / "docs" / "figures" / figname
    fig.savefig(out, dpi=120, bbox_inches="tight")
    print("wrote", out)


if __name__ == "__main__":
    tag = sys.argv[1] if len(sys.argv) > 1 else "200day"
    if tag not in WINDOWS:
        raise SystemExit(f"usage: {sys.argv[0]} [{'|'.join(WINDOWS)}]")
    run(tag)
